arm:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  


  #Group Velocity Controller
  joint_group_velocity_controller:
    type: velocity_controllers/JointGroupVelocityController
    joints:
        - arm_1_joint
        - arm_2_joint
        - arm_3_joint
        - arm_4_joint
        - arm_5_joint
        - arm_6_joint

  #velocity trajectory controller
  joint_trajectory_controller:
    type: velocity_controllers/JointTrajectoryController
    joints:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - arm_6_joint
    gains:
      arm_1_joint: {p: 100, d: 1, i: 0.01}
      arm_2_joint: {p: 100, d: 1, i: 0.01}
      arm_3_joint: {p: 100, d: 1, i: 0.01}
      arm_4_joint: {p: 100, d: 1, i: 0.01}
      arm_5_joint: {p: 100, d: 1, i: 0.01}
      arm_6_joint: {p: 100, d: 1, i: 0.01}
