# powercube_chain parameters
can_module: PCAN
can_device: /dev/pcan32 #pcan34 should be the right one . . . (check with cat/proc/pcan)
can_baudrate: 500 #this is strange, nothing but 500 works . . .
modul_ids: [1,2,3,4,5,6] #try changing to can't get to the last joint . . .
joint_names: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint]
max_accelerations: [0.4,0.4,0.4,0.4,0.4,0.4]
min_publish_duration: 0.01 # careful
horizon: 0.1 # [s]
frequency: 100
# force_use_movevel: true

# trajectory controller parameters
# ptp_vel: 0.4 # rad/sec
# ptp_acc: 0.2 # rad/sec^2
# max_error: 0.15 # rad
