# powercube_chain parameters
can_module: PCAN
can_device: /dev/pcan34 #pcan34 should be the right one . . .
can_baudrate: 500 
modul_ids: [3,4,5,6,7,8,9] # 7 does not init . . . (8, 9 probably) try changing to [3/4 4/5 5/6 6/7 7/8 8/9] if not initializeing, or just run mod 1 with ids 1--9 and see that happns
joint_names: [arm_1_joint, arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint]
max_accelerations: [0.8,0.8,0.8,0.8,0.8,0.8,0.8]
min_publish_duration: 0.1
horizon: 0.1 # [s]
frequency: 68

# trajectory controller parameters
ptp_vel: 0.4 # rad/sec
ptp_acc: 0.2 # rad/sec^2
max_error: 0.15 # rad
