<?xml version="1.0"?>
<robot name="arm" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Constants for robot dimensions -->

  <xacro:include filename="$(find lwa_lab_robot)/calibration/calibration.urdf.xacro" />
  <xacro:include filename="$(find lwa_lab_robot)/urdf/materials.urdf.xacro" />




  <xacro:property name="PI" value="3.1415926535897931"/>

  <xacro:property name="M_PI" value="3.1415926535897931"/>

  <xacro:property name="safety_offset" value="0.01"/>

  <xacro:property name="width" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height1" value="2" /> <!-- Link 1 -->
  <xacro:property name="height2" value="1" /> <!-- Link 2 -->
  <xacro:property name="height3" value="1" /> <!-- Link 3 -->
  <xacro:property name="camera_link" value="0.1" /> <!-- Size of square 'camera' box -->
  <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->

  <xacro:property name="base_mass" value="40.0"/>
  <xacro:property name="base_length" value="1.0"/>
  <xacro:property name="base_width" value="0.5"/>
  <xacro:property name="base_height" value="0.25"/>
  <xacro:property name="wheelbase" value="0.6"/>

  <xacro:property name="wheel_radius" value="0.2"/>
  <xacro:property name="wheel_height" value="0.1"/>
  <xacro:property name="wheel_mass" value="2.0"/>
  <xacro:property name="wheel_x_offset" value="0.35" />
  <xacro:property name="wheel_y_offset" value="0.3" />
  <xacro:property name="wheel_z_offset" value="-0.05" />
  
  <xacro:property name="table_height_offset" value="0.62" />


  <macro name="box_inertia" params="m x y z">
    <inertia  ixx="${m*(y*y+z*z)/12+(1e-6)}" ixy="0" ixz="0" iyy="${m*(x*x+z*z)/12+(1e-6)}" iyz="0" izz="${m*(x*x+z*z)/12+(1e-6)}" />
  </macro>

  <macro name="cylinder_inertia" params="m r h">
    <inertia  ixx="${m*(3*r*r+h*h)/12+(1e-6)}" ixy="0" ixz="0" iyy="${m*(3*r*r+h*h)/12+(1e-6)}" iyz="0" izz="${m*r*r/2+(1e-6)}" />
  </macro>
  
  
  
  
  
  <xacro:macro name="make_transmission" params="name">

    <transmission name="${name}_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${name}_joint">
        <hardwareInterface>VelocityJointInterface</hardwareInterface>
      </joint>
      <actuator name="${name}_motor">
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro>
  
  
  <link name="world"/>
  
  <joint name="world_table_fixed" type="fixed">
    <parent link="world"/>
    <child link="robot_base_link"/>
    <origin xyz="0 0 ${table_height_offset}" rpy="0 0 0"/>
  </joint>
  
  
  
  <link name="robot_base_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <!-- <box size="1.0 0.5 0.25"/> -->
        <mesh filename="package://lwa_lab_robot/cad/components/table_s.stl" />
      </geometry>
    </collision>

    <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://lwa_lab_robot/cad/components/table_s.stl" />
        </geometry>
        <material name="Schunk/DarkGolden" />
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${base_mass}"/>
      <box_inertia m="${base_mass}" x="${base_length}" y="${base_width}" z="${base_height}"/>
    </inertial>
  </link>


  
  
    <joint name="table_mount_joint" type="fixed">
    <parent link="robot_base_link"/>
    <child link="arm_base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
  </joint>
  
  

    <link name="arm_base_link">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1.0"/>
        <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
      </inertial>

      <visual>
        <origin xyz="0 0 0.004" rpy="0 0 0" />
        <geometry>
          <cylinder radius="0.045" length="0.08"/>
        </geometry>
        <material name="Schunk/Blue" />
      </visual>

      <collision>
        <origin xyz="0 0 0.005" rpy="0 0 0" />
        <geometry>
          <box size="0.01 0.01 0.01"/>
        </geometry>
      </collision>
    </link>
    
    
    
    
    
    
    
    <joint name="arm_1_joint" type="revolute">
        <origin xyz="0 0 0.008" rpy="0 0 0"/>
        <parent link="arm_base_link"/>
        <child link="arm_1_link"/>
        <axis xyz="0 0 -1"/>
        <calibration rising="${arm_1_ref}"/>
        <limit effort="216" velocity="0.43633" lower="${-M_PI+safety_offset}" upper="${M_PI-safety_offset}"/>
    </joint>
    <xacro:make_transmission name="arm_1"/>
    
    <link name="arm_1_link">
        <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="2.0"/>
        <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
        </inertial>

        <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <mesh filename="package://lwa_lab_robot/cad/components/link_1_s.stl" />
        </geometry>
        <material name="Schunk/DarkGolden" />
        </visual>

        <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
            <mesh filename="package://lwa_lab_robot/cad/components/link_1_s.stl" />
        </geometry>
        </collision>
    </link>
    
    
    
    
    
    
    
    
    <!-- joint between arm_1_link and arm_2_link -->
    <joint name="arm_2_joint" type="revolute">
      <origin xyz="0 0 ${(210.4+37.5)/1000}" rpy="0 0 3.1415"/>
      <parent link="arm_1_link"/>
      <child link="arm_2_link"/>
      <axis xyz="0 1 0"/>
      <calibration rising="${arm_2_ref}"/>      
      <limit effort="216" velocity="0.43633" lower="${-2.14 + safety_offset}" upper="${2.14 - safety_offset}"/>
    </joint>
    <xacro:make_transmission name="arm_2"/>

    <link name="arm_2_link">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="2.0"/>
        <inertia ixx="0.03" ixy="0" ixz="0" iyy="0.03" iyz="0" izz="0.03" />
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://lwa_lab_robot/cad/components/link_2_s.stl" />
        </geometry>
        <material name="Schunk/DarkGolden" />
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://lwa_lab_robot/cad/components/link_2_s.stl"/>
        </geometry>
      </collision>
    </link>
    
    
    
    <!-- joint between arm_2_link and arm_3_link -->
    <joint name="arm_3_joint" type="revolute">
      <origin xyz="0 0 ${(100-8)/1000}" rpy="0 0 0"/>
      <parent link="arm_2_link"/>
      <child link="arm_3_link"/>
      <axis xyz="0 0 -1"/>
      <calibration rising="${arm_3_ref}"/>
      <limit effort="81.5" velocity="0.4189" lower="${-M_PI + safety_offset}" upper="${M_PI - safety_offset}"/>
      <!-- <dynamics damping="5" /> -->
      <!-- <limit effort="176" velocity="2.0" lower="-6.25" upper="6.25"/> -->
      <!-- <safety_controller k_position="20" k_velocity="25" soft_lower_limit="${-6.25 + 0.01}" soft_upper_limit="${6.25 - 0.01}" /> -->
    </joint>
    <xacro:make_transmission name="arm_3"/>
    
    <link name="arm_3_link">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="2.0"/>
        <inertia ixx="0.03" ixy="0" ixz="0" iyy="0.03" iyz="0" izz="0.03" />
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://lwa_lab_robot/cad/components/link_3_s.stl" />
        </geometry>
        <material name="Schunk/DarkGolden" />
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://lwa_lab_robot/cad/components/link_3_s.stl"/>
        </geometry>
      </collision>
    </link>
    
    
    <!-- joint between arm_3_link and arm_4_link -->
    <joint name="arm_4_joint" type="revolute">
      <origin xyz="0 0 ${(176+30)/1000}" rpy="0 0 3.1415" />
      <parent link="arm_3_link"/>
      <child link="arm_4_link"/>
      <axis xyz="0 1 0" />
      <calibration rising="${arm_4_ref}"/>
      <limit effort="81.5" velocity="0.4189" lower="${-2.18 + safety_offset}" upper="${2.18 - safety_offset}"/>
      <!-- <dynamics damping="5" /> -->
      <!-- <limit effort="176" velocity="2.0" lower="-1.97" upper="1.97"/> -->
      <!-- <safety_controller k_position="20" k_velocity="25" soft_lower_limit="${-1.97 + 0.01}" soft_upper_limit="${1.97 - 0.01}" /> -->
    </joint>
    <xacro:make_transmission name="arm_4"/>
    
    <link name="arm_4_link">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="2.0"/>
        <inertia ixx="0.03" ixy="0" ixz="0" iyy="0.03" iyz="0" izz="0.03" />
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://lwa_lab_robot/cad/components/link_4_s.stl"/>
        </geometry>
        <material name="Schunk/DarkGolden" />
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://lwa_lab_robot/cad/components/link_4_s.stl"/>
        </geometry>
      </collision>
    </link>
    
    
    <!-- joint between arm_4_link and arm_5_link -->
    <joint name="arm_5_joint" type="revolute">
      <origin xyz="0 0 0.17" rpy="0 0 0" />
      <parent link="arm_4_link"/>
      <child link="arm_5_link"/>
      <axis xyz="0 -1 0" />
      <calibration rising="${arm_5_ref}"/>
      <limit effort="20.7" velocity="0.43633" lower="${-M_PI + safety_offset}" upper="${M_PI - safety_offset}"/>
      <!-- <dynamics damping="5" /> -->
      <!-- <limit effort="20.1" velocity="2.0" lower="-1.97" upper="1.97" /> -->
      <!-- <safety_controller k_position="20" k_velocity="25" soft_lower_limit="${-1.97 + 0.01}" soft_upper_limit="${1.97 - 0.01}" /> -->
    </joint>
    <xacro:make_transmission name="arm_5"/>

    <link name="arm_5_link">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="2.057856"/>
        <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://lwa_lab_robot/cad/components/link_5_s.stl" />
        </geometry>
        <material name="Schunk/DarkGolden" />
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://lwa_lab_robot/cad/components/link_5_s.stl"/>
        </geometry>
      </collision>
    </link>
    
    
    
    <!-- joint between arm_5_link and arm_6_link -->
    <joint name="arm_6_joint" type="revolute">
      <origin xyz="0 0 ${(80-3.4)/1000}" rpy="0 0 0" />
      <parent link="arm_5_link"/>
      <child link="arm_6_link"/>
      <axis xyz="0 0 -1" />
      <calibration rising="${arm_6_ref}"/>
      <limit effort="15" velocity="1.2566" lower="${-2.0 + safety_offset}" upper="${2.0 - safety_offset}"/>
    </joint>
    <xacro:make_transmission name="arm_6"/>

    <link name="arm_6_link">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="1.120198"/>
        <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://lwa_lab_robot/cad/components/link_6_s.stl" />
        </geometry>
        <material name="Schunk/DarkGolden" />
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://lwa_lab_robot/cad/components/link_6_s.stl"/>
        </geometry>
      </collision>
    </link>
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/arm</robotNamespace>
            <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
        </plugin>
    </gazebo>







</robot>
